name: 'Build Plugin'
description: "Builds the Plugin"

inputs:
  shopware:
    description: "The Shopware version that is used to build the plugin"
    required: true

runs:
  using: "composite"
  steps:

    - name: Install Shopware CLI
      shell: bash
      run: |
        curl -1sLf 'https://dl.cloudsmith.io/public/friendsofshopware/stable/setup.deb.sh' | sudo -E bash && sudo apt install shopware-cli

    - name: Upload into Docker
      shell: bash
      run: |
        mkdir -p $(pwd)/../html/custom/plugins/MolliePayments
        mv -v $(pwd)/* $(pwd)/../html/custom/plugins/MolliePayments

    # --------------------------------------------------------------------------------------------------------------------------------------

    - name: Build Plugin
      shell: bash
      run: |
        cd $(pwd)/../html/custom/plugins/MolliePayments && make release

    # --------------------------------------------------------------------------------------------------------------------------------------

    - name: Copy ZIP File
      shell: bash
      run: |
        cp $(pwd)/../html/custom/plugins/.build/MolliePayments.zip ~/.build/MolliePayments.zip

    - name: Store ZIP file in Github
      uses: actions/upload-artifact@v2
      with:
        name: MolliePayments-Shopware-${{ inputs.shopware }}
        retention-days: 4
        path: ~/.build
