name: _ Cypress Tests

on:
  workflow_call:
    inputs:
      shopware:
        required: true
        type: string
      php:
        required: true
        type: string
      filters:
        required: true
        type: string
      testrail:
        required: true
        type: boolean


env:
  SHOP_URL: https://local.mollie.shop


jobs:

  e2e:
    runs-on: ubuntu-latest
    steps:

      - name: Install Cypress
        run: cd tests/Cypress && make install -B

      - name: Start Cypress | Filters ${{ inputs.filters }}
        if: "${{ github.event.inputs.filters != '' }}"
        run: |
          cd tests/Cypress && \
          make run shopware=${{ inputs.shopware }} storeApiKey=${{ inputs.storeApiKey }} url=$SHOP_URL filters=${{ inputs.filters }}

      - name: Start Cypress
        if: "${{ github.event.inputs.testrail == false }}"
        run: |
          cd tests/Cypress && \
          make run shopware=${{ inputs.shopware }} storeApiKey=${{ inputs.storeApiKey }} url=$SHOP_URL

      - name: Start Cypress with TestRail
        if: "${{ github.event.inputs.testrail == true }}"
        run: |
          cd tests/Cypress && \
          CYPRESS_TESTRAIL_DOMAIN=${{ secrets.TESTRAIL_DOMAIN }} \
          CYPRESS_TESTRAIL_USERNAME=${{ secrets.TESTRAIL_USERNAME }} \
          CYPRESS_TESTRAIL_PASSWORD=${{ secrets.TESTRAIL_PASSWORD }} \
          CYPRESS_TESTRAIL_PROJECT_ID=7 \
          CYPRESS_TESTRAIL_MILESTONE_ID=15 \
          CYPRESS_TESTRAIL_RUN_NAME="Github Workflow __datetime__, ${{ github.event.head_commit.message }}, Shopware ${{ matrix.shopware }}" \
          CYPRESS_TESTRAIL_RUN_CLOSE=true \
          make run shopware=${{ matrix.shopware }} storeApiKey=$STORE_API_KEY url=$SHOP_URL 

      - name: Download Logs
        if: ${{ always() }}
        run: |
          mkdir -p $(pwd)/tests/Cypress/cypress/logs/shopware
          mkdir -p $(pwd)/tests/Cypress/cypress/logs/apache
          docker cp shop:/var/www/html/var/log/. $(pwd)/tests/Cypress/cypress/logs/shopware
          docker cp shop:/var/log/php/. $(pwd)/tests/Cypress/cypress/logs/apache

      - name: Store Cypress Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress_results_sw_v${{ inputs.shopware }}
          retention-days: 1
          path: |
            tests/Cypress/cypress/results
            tests/Cypress/cypress/logs
            tests/Cypress/cypress/videos
            tests/Cypress/cypress/screenshots