name: _ Build Plugin

on:
  workflow_call:
    inputs:
      pluginVersion:
        description: "An optional specific plugin version that will be used to checkout the source code"
        type: string
        default: ''
        required: false
      shopware:
        description: "The Shopware version that is used to run the Cypress tests."
        type: string
        required: true


jobs:

  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        if: "${{ github.event.inputs.pluginVersion == '' }}"
        uses: actions/checkout@v2

      - name: Clone Code for Plugin v${{ inputs.pluginVersion }}
        if: "${{ github.event.inputs.pluginVersion != '' }}"
        uses: actions/checkout@v2
        with:
          ref: refs/tags/v${{ inputs.pluginVersion }}

      # --------------------------------------------------------------------------------------------------------------------------------------

      - name: Create Cache Directories
        run: |
          mkdir -p ~/.build

      - name: Mount Build Cache
        id: cache-build
        uses: actions/cache@v3
        with:
          key: cache-plugin
          path: ~/.build

      # --------------------------------------------------------------------------------------------------------------------------------------

      - name: Start Docker
        run: |
          docker run --rm --name shop -d dockware/dev:${{ inputs.shopware }}
          sleep 20
          docker logs shop

      - name: Update Shopware Config
        run: |
          docker exec shop bash -c 'sed -i "s/APP_ENV=dev/APP_ENV=prod/g" /var/www/html/.env' || true;

      - name: Upload into Docker
        run: |
          docker cp $(pwd)/. shop:/var/www/html/custom/plugins/MolliePayments
          docker exec shop bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'

      # --------------------------------------------------------------------------------------------------------------------------------------

      - name: Build Plugin
        run: |
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/MolliePayments && make release'

      # --------------------------------------------------------------------------------------------------------------------------------------

      - name: Download ZIP File
        run: |
          docker cp shop:/var/www/html/custom/plugins/.build/MolliePayments.zip ~/.build/MolliePayments.zip

      - name: Store ZIP file in Github
        uses: actions/upload-artifact@v2
        with:
          name: MolliePaymentsRelease
          retention-days: 4
          path: ~/.build
