name: _ PHP Tests

on:
  workflow_call:


env:
  STORE_API_KEY: SWSCOVFSNKLBYUTKS1VSOEDTUQ
  BUILD_SW_VERSION: 6.4.16.0


jobs:

  php_checks:
    name: PHP Syntax Checks
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: PHP Syntax Checks
        run: make phpcheck -B

  php_min:
    name: PHP 7.2 Compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Dev-Dependencies Cache
        uses: actions/cache@v3
        with:
          key: cache-dependencies
          path: |
            src/Resources/app/administration/node_modules
            src/Resources/app/storefront/node_modules
            vendor

      - name: PHP Compatibility Checks
        run: make phpmin -B

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Dev-Dependencies Cache
        uses: actions/cache@v3
        with:
          key: cache-dependencies
          path: |
            src/Resources/app/administration/node_modules
            src/Resources/app/storefront/node_modules
            vendor

      - name: Run PHPUnit
        run: make phpunit -B

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Dev-Dependencies Cache
        uses: actions/cache@v3
        with:
          key: cache-dependencies
          path: |
            src/Resources/app/administration/node_modules
            src/Resources/app/storefront/node_modules
            vendor

      - name: Run PHPStan
        run: make stan -B

  phpcsfixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Dev-Dependencies Cache
        uses: actions/cache@v3
        with:
          key: cache-dependencies
          path: |
            src/Resources/app/administration/node_modules
            src/Resources/app/storefront/node_modules
            vendor

      - name: Run PHP CS Fixer
        run: make csfix -B

  infection:
    name: Mutation Tests
    needs: phpunit
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Dev-Dependencies Cache
        uses: actions/cache@v3
        with:
          key: cache-dependencies
          path: |
            src/Resources/app/administration/node_modules
            src/Resources/app/storefront/node_modules
            vendor

      - name: Run Infection
        run: make infection -B
