name: Build ZIP File

on:
  workflow_dispatch:

jobs:

  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Build Plugin
        uses: ./.github/actions/build-plugin
