name: CI Pipeline


on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:

  install:
    uses: ./.github/workflows/pipeline_install_dev.yml

  # ------------------------------------------------------------------------------------------------------------------------

  javascript:
    uses: ./.github/workflows/_pipeline_js.yml
    needs: [ install ]

  # ------------------------------------------------------------------------------------------------------------------------

  php:
    uses: ./.github/workflows/_pipeline_php.yml
    needs: [ install ]

  # ------------------------------------------------------------------------------------------------------------------------

  build:
    uses: ./.github/workflows/_pipeline_build.yml
    with:
      shopware: 6.4.16.0

  e2e:
    name: E2E Tests | Shopware ${{ matrix.shopware }}, PHP ${{ matrix.php }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - shopware: '6.4.16.0'
            php: '8.1'
          - shopware: '6.4.15.2'
            php: '8.1'
          - shopware: '6.4.15.1'
            php: '8.1'
          - shopware: '6.4.14.0'
            php: '8.1'
          - shopware: '6.4.12.0'
            php: '8.0'
          - shopware: '6.4.11.1'
            php: '8.0'
          - shopware: '6.4.10.0'
            php: '8.0'
          - shopware: '6.4.9.0'
            php: '7.4'
          - shopware: '6.4.8.2'
            php: '7.4'
          - shopware: '6.4.7.0'
            php: '7.4'
          - shopware: '6.4.6.1'
            php: '7.4'
          - shopware: '6.4.5.1'
            php: '7.4'
          - shopware: '6.4.4.1'
            php: '7.4'
          - shopware: '6.4.2.1'
            php: '7.4'
          - shopware: '6.4.1.2'
            php: '7.4'
          - shopware: '6.3.5.2'
            php: '7.2'
    steps:

      - name: E2E Tests
        uses: ./.github/workflows/_pipeline_cypress.yml
        with:
          shopware: ${{ matrix.shopware }}
          php: ${{ matrix.php }}
          # we want to send results to testrail here
          testrail: true

  build_tests:
    name: Building Tests | Shopware ${{ matrix.shopware }}
    needs: [ build, e2e ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shopware: [ '6.4.0.0', '6.3.0', '6.2.0', '6.1.0' ]
    steps:

      - name: Installation Tests
        uses: ./.github/workflows/_pipeline_cypress.yml
        with:
          shopware: ${{ matrix.shopware }}
          php: 8.1
          # only do installation tests without cypress here
          runCypress: false
