name: Compatibility Pipeline
run-name: Shopware ${{ github.event.inputs.swVersion }}, PHP ${{ github.event.inputs.phpVersion }}



on:
  workflow_dispatch:
    inputs:
      swVersion:
        description: 'Shopware Version'
        required: true
      phpVersion:
        description: 'PHP Version'
        required: true

jobs:

  e2e:
    name: Plugin v${{ matrix.plugin }} | Shopware ${{ github.event.inputs.swVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin: [ '3.1.0', '3.0.0', '2.5.0' ]
    steps:

      - name: Clone Code
        uses: actions/checkout@v2
        with:
          ref: refs/tags/v${{ matrix.plugin }}

      - name: Create Cache Directories
        run: |
          mkdir -p ~/.build

      - name: Mount Build Cache
        id: cache-build
        uses: actions/cache@v3
        with:
          key: cache-plugin
          path: ~/.build

      - name: Build Plugin ${{ matrix.plugin }}
        uses: ./.github/workflows/action_build.yml
        with:
          shopware: ${{ github.event.inputs.swVersion }}

      - name: Run Cypress for Plugin ${{ matrix.plugin }}
        uses: ./.github/workflows/action_e2e.yml
        with:
          secrets: inherit
          shopware: ${{ matrix.shopware }}
          php: 8.1
          # make sure to use old cypress tests of that plugin version
          pluginVersion: ${{ matrix.plugin }}
          # we have to remove old tests from the history, because e.g.
          # SEPA Direct Debit is not working anymore when being executed now...
          removeDeprecatedTests: true
