name: Compatibility Pipeline
run-name: Shopware ${{ github.event.inputs.swVersion }}, PHP ${{ github.event.inputs.phpVersion }}

on:
  workflow_dispatch:
    inputs:
      swVersion:
        description: 'Shopware Version'
        required: true
      phpVersion:
        description: 'PHP Version'
        required: true

jobs:

  e2e:
    name: Plugin v${{ matrix.plugin }} | Shopware ${{ github.event.inputs.swVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin: [ '3.1.0', '3.0.0', '2.5.0' ]
    steps:

      - name: Clone Code
        uses: actions/checkout@v3
        with:
          ref: refs/tags/v${{ matrix.plugin }}

      - name: Create Cache Directories
        run: |
          mkdir -p ~/.build

      - name: Mount Build Cache, cache-plugin-${{ github.run_id }}-plugin-${{ matrix.plugin }}
        uses: actions/cache@v3
        with:
          key: cache-plugin-${{ github.run_id }}-plugin-${{ matrix.plugin }}
          path: ~/.build

      - name: Build Plugin, Shopware ${{ github.event.inputs.swVersion }}
        uses: ./.github/actions/build-plugin
        with:
          shopware: ${{ github.event.inputs.swVersion }}

      - name: Run Cypress for Plugin ${{ matrix.plugin }}
        uses: ./.github/actions/run-e2e
        with:
          # -------------------------------------------
          SHOPWARE: ${{ github.event.inputs.swVersion }}
          PHP: ${{ github.event.inputs.phpVersion }}
          # -------------------------------------------
          MOLLIE_APIKEY_TEST: ${{ secrets.MOLLIE_APIKEY_TEST }}
          # -------------------------------------------
          TESTRAIL: false
          # we have to remove old tests from the history, because e.g.
          # SEPA Direct Debit is not working anymore when being executed now...
          REMOVE_DEPRECATED_TESTS: true
