name: Compatibility Pipeline
run-name: Shopware ${{ github.event.inputs.swVersion }}, PHP ${{ github.event.inputs.phpVersion }}

on:
  workflow_dispatch:
    inputs:
      swVersion:
        description: 'Shopware Version'
        required: true
      phpVersion:
        description: 'PHP Version'
        required: true


jobs:

  e2e:
    name: Plugin v${{ matrix.plugin }} | Shopware ${{ github.event.inputs.swVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin: [ '3.2.0', '3.1.0', '3.0.0', '2.5.0' ]
    steps:

      - name: Clone Code
        uses: actions/checkout@v2
        with:
          ref: refs/tags/v${{ matrix.plugin }}

      - name: Build Plugin
        uses: ./.github/workflows/pipeline_build.yml
        with:
          shopware: ${{ github.event.inputs.swVersion }}

      - name: Remove deprecated Cypress Tests
        run: |
          # SEPA Direct Debit has been completely removed from Mollie. We have to remove that entry from the tests in old Cypress versions
          sed -i "/key: 'directdebit'/g" $(pwd)/tests/Cypress/cypress/e2e/storefront/checkout/checkout-success.cy.js || true
          sed -i "/key: 'directdebit'/g" $(pwd)/tests/Cypress/cypress/integration/storefront/checkout/checkout-success.spec.js || true

      - uses: ./.github/workflows/_pipeline_docker.yml
        with:
          shopware: ${{ github.event.inputs.swVersion }}
          php: ${{ github.event.inputs.phpVersion }}
          storeApiKey: 'SWSCOVFSNKLBYUTKS1VSOEDTUQ'
          zipFile: '~/.build/MolliePayments.zip'

      - uses: ./.github/workflows/_pipeline_cypress.yml
        with:
          shopware: ${{ github.event.inputs.swVersion }}
          php: ${{ github.event.inputs.phpVersion }}
          storeApiKey: 'SWSCOVFSNKLBYUTKS1VSOEDTUQ'
          filters: ""
          testrail: false