name: E2E Playground
run-name: Shopware ${{ github.event.inputs.swVersion }}, PHP ${{ github.event.inputs.phpVersion }}


on:
  workflow_dispatch:
    inputs:
      swVersion:
        description: 'Shopware Version'
        required: true
      phpVersion:
        description: 'PHP Version'
        required: true

jobs:


  build:
    name: Build Plugin
    needs: install
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v2

      - name: Create Cache Directories
        run: |
          mkdir -p ~/.build

      - name: Mount Build Cache
        uses: actions/cache@v3
        with:
          key: cache-plugin
          path: ~/.build

      - name: Build Plugin
        uses: ./.github/actions/build-plugin
        with:
          shopware: ${{ github.event.inputs.swVersion }}

  e2e:
    name: E2E Tests | Shopware ${{ github.event.inputs.swVersion }}, PHP ${{ github.event.inputs.phpVersion }}
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v2

      - name: Mount Build Cache
        id: cache-build
        uses: actions/cache@v3
        with:
          key: cache-plugin
          path: ~/.build

      - name: E2E Tests, Shopware ${{ matrix.shopware }}
        uses: ./.github/actions/run-e2e
        with:
          # -------------------------------------------
          SHOPWARE: ${{ github.event.inputs.swVersion }}
          PHP: ${{ github.event.inputs.phpVersion }}
          # -------------------------------------------
          RUN_CYPRESS: true
          MOLLIE_APIKEY_TEST: ${{ secrets.MOLLIE_APIKEY_TEST }}
          # -------------------------------------------
          TESTRAIL: true
          TESTRAIL_DOMAIN: ${{ secrets.TESTRAIL_DOMAIN }}
          TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
          TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}