name: E2E Playground
run-name: Shopware ${{ github.event.inputs.swVersion }}, PHP ${{ github.event.inputs.phpVersion }}


on:
  workflow_dispatch:
    inputs:
      swVersion:
        description: 'Shopware Version'
        required: true
      phpVersion:
        description: 'PHP Version'
        required: true

jobs:

  build:
    uses: ./.github/workflows/_pipeline_build.yml
    with:
      shopware: ${{ github.event.inputs.swVersion }}

  e2e:
    uses: ./.github/workflows/_pipeline_cypress.yml
    needs: [ build ]
    with:
      shopware: ${{ github.event.inputs.swVersion }}
      php: ${{ github.event.inputs.phpVersion }}
      filter: ""

