name: E2E Playground
run-name: Shopware ${{ github.event.inputs.swVersion }}, PHP ${{ github.event.inputs.phpVersion }}


on:
  workflow_dispatch:
    inputs:
      swVersion:
        description: 'Shopware Version'
        required: true
      phpVersion:
        description: 'PHP Version'
        required: true

jobs:

  build:
    uses: ./.github/workflows/_pipeline_build.yml
    with:
      shopware: ${{ github.event.inputs.swVersion }}

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v2

      - name: Mount Build Cache
        id: cache-build
        uses: actions/cache@v3
        with:
          key: cache-plugin
          path: ~/.build

      - uses: ./.github/workflows/_pipeline_docker.yml
        with:
          shopware: ${{ github.event.inputs.swVersion }}
          php: ${{ github.event.inputs.phpVersion }}
          storeApiKey: 'SWSCOVFSNKLBYUTKS1VSOEDTUQ'
          zipFile: '~/.build/MolliePayments.zip'

      - uses: ./.github/workflows/_pipeline_cypress.yml
        with:
          shopware: ${{ github.event.inputs.swVersion }}
          php: ${{ github.event.inputs.phpVersion }}
          storeApiKey: 'SWSCOVFSNKLBYUTKS1VSOEDTUQ'
          filters: ""
          testrail: false





