name: PR Pipeline

on: [ pull_request, workflow_dispatch ]


jobs:

  install:
    uses: ./.github/workflows/pipeline_install_dev.yml

  # ------------------------------------------------------------------------------------------------------------------------

  javascript:
    uses: ./.github/workflows/pipeline_js.yml
    needs: [ install ]

  # ------------------------------------------------------------------------------------------------------------------------

  php:
    uses: ./.github/workflows/pipeline_php.yml
    needs: [ install ]

  # ------------------------------------------------------------------------------------------------------------------------

  build:
    uses: ./.github/workflows/_pipeline_build.yml
    with:
      shopware: 6.4.16.0

  # ------------------------------------------------------------------------------------------------------------------------

  integration:
    name: Integration Tests | Shopware ${{ matrix.shopware }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shopware: [ '6.4.16.0', '6.4.15.0', '6.4.9.0', '6.4.8.2', '6.4.0.0', '6.3.0', '6.2.0', '6.1.0' ]
    steps:

      - name: Installation Tests
        uses: ./.github/workflows/_pipeline_cypress.yml
        with:
          shopware: ${{ matrix.shopware }}
          php: 8.1
          # only do installation tests, no cypress for this simple testing
          runCypress: false

  # ------------------------------------------------------------------------------------------------------------------------

  e2e:
    name: E2E Core Tests
    needs: build
    uses: ./.github/workflows/_pipeline_cypress.yml
    with:
      shopware: 6.4.16.0
      php: 8.1
      # only run @core tests, because we have no API key here
      filters: "@core"
      # do not send to testrail for PR tests
      testrail: false